- name: check ospf neighbor
  hosts: all
  gather_facts: false
  tasks:
    - name: sh ospf neighbor
      ios_command:
        commands:
          - sh ip ospf neighbor
    #    register: output1
    
