- name: Show Command
  hosts: R1
  gather_facts: false



  tasks:
    - name: make interface down
      ios_interface:
          name: GigabitEthernet0/1
          #name: "{{ Device-interface }}"
          enabled: False

    - name: make interface up
      ios_interface:
          name: GigabitEthernet0/1
          #name: "{{ Device-interface }}"
          enabled: True

