- name: ping module demo
  hosts: all
  become: false
  tasks:
    - name: test connection
      ansible.builtin.ping:
       
    - name: run multiple commands on remote nodes
      ios_command:
        commands:
          - show ip int br
          - show ip route
