- name: Hello World Sample
  hosts: R1
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
       
    - name: run multiple commands on remote nodes
      ios_command:
        commands:
          - show ip int br
          - show ip route
