- name: ping module demo
  hosts: Router
  become: false
  tasks:
    #- name: test connection
    #  ansible.builtin.ping:
    
    #- name: Pinging Host
    #  action: ping
      
    - name: Execute ping
      shell: "traceroute 192.168.10.102"
      register: result
      
    - name: Show result
      debug:
        msg:"{{ result['stdout_lines'] }}"
