- name: Show Command
  hosts: all
  gather_facts: false
  tasks:
    - name: show interface
      ios_command:
        commands:
          - show ip inter br
      #  register: output1
    
    - name: show log
      ios_command:
        commands:
          - show log | include down
      #  register: output

    - name: show CPU History
      ios_command:
        commands:
          - show processes cpu history


      
    #- name: run multiple commands on remote nodes
    #  ios_command:
    #    commands:
    #      - show version
    #      - show interfaces

    #- name: test connection
    #  ansible.builtin.ping:
    
    #- name: Pinging Host
    #  action: ping
      
    #- name: Execute ping
    #  shell: "traceroute 192.168.10.102"
    #  register: result
      
    #- name: Show result
    #  debug:
    #    msg:"{{ result['stdout_lines'] }}"
