---
- hosts: R1
  gather_facts: false
  connection: local

  tasks:
   - name: run show version on ios device
     ios_command:
       commands:
         - show version
         - show ip int br
       host: "{{ inventory_hostname }}"
       username: majid
       password: majid123
