- name: Hello World Sample
  hosts: Router
  tasks:
    - name: show interface and log
      ios_command:
        commands:
          - show log | include down
          - show interfaces
       
    #- name: run multiple commands on remote nodes
    #  ios_command:
    #    commands:
    #      - show version
    #      - show interfaces

    #- name: test connection
    #  ansible.builtin.ping:
    
    #- name: Pinging Host
    #  action: ping
      
    #- name: Execute ping
    #  shell: "traceroute 192.168.10.102"
    #  register: result
      
    #- name: Show result
    #  debug:
    #    msg:"{{ result['stdout_lines'] }}"
