- name: Add VLAN
  hosts: all
  gather_facts: false
  tasks:
    - name: show vlan
      ios_command:
        commands:
          - show vlan
    #    register: output1
    
    - name: Create vlan
      ios_vlan:
        vlan_id: 100
        name: IT
        state: present