- name: Add VLAN
  hosts: all
  gather_facts: false
  tasks:
    #- name: show interface
    #  ios_command:
    #    commands:
    #      - show ip inter br
    #    register: output1
    
    - name: Create vlan
      ios_vlan:
      vlan_id: 100
      name: IT
      state: present